name: Code Quality

on:
  push:
    branches: [ main, master, develop, claude/** ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-lint-${{ hashFiles('requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-lint-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy
        pip install -r requirements.txt

    - name: Run flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 scm_dashboard_v9 --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 scm_dashboard_v9 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Check code formatting with black
      run: |
        black --check --diff scm_dashboard_v9

    - name: Check import sorting with isort
      run: |
        isort --check-only --diff scm_dashboard_v9

    - name: Run mypy type checking
      run: |
        mypy scm_dashboard_v9 --ignore-missing-imports --no-strict-optional || true

  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit[toml]

    - name: Run security checks with bandit
      run: |
        bandit -r scm_dashboard_v9 -ll -f json -o bandit-report.json || true
        bandit -r scm_dashboard_v9 -ll || true

    - name: Upload security report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bandit-security-report
        path: bandit-report.json
