name: v7-tests

on:
  push:
    branches: [ v5-modul-cursor ]
  pull_request:
    branches: [ v5-modul-cursor ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Generate golden (if absent)
        run: |
          if [ ! -f tests_v7/golden/v5/timeline_with_consumption.csv ]; then 
            UPDATE_GOLDEN=1 pytest -q tests_v7/test_v7_golden_equivalence.py || true
          fi

      - name: Run tests (v7)
        run: |
          pytest -q tests_v7/test_v7_golden_equivalence.py


