[gs_proxy]
webapp_url = "https://script.google.com/macros/s/AKfycbxxgV8uLrVD7FNLA0ntnL8KNVKre99RDFq3LzDjPijkMAm5LoGDRGNwif7eD2h0VqzSIA/exec"
sheet_id   = "1RYjKW2UDJ2kWJLAqQH26eqx2-r9Xb0_qE_hfwu9WIj8"
token      = "BOOSTERS_MINI_TOKEN_SCM_DASHBOARD_20250929"
timeout_s  = 15
